# Generated by Django 4.2.6 on 2023-11-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
